/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAmbulanceWlList {
    }
}
declare global {
    interface HTMLAppAmbulanceWlListElement extends Components.AppAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLAppAmbulanceWlListElement: {
        prototype: HTMLAppAmbulanceWlListElement;
        new (): HTMLAppAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "app-ambulance-wl-list": HTMLAppAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface AppAmbulanceWlList {
    }
    interface IntrinsicElements {
        "app-ambulance-wl-list": AppAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-ambulance-wl-list": LocalJSX.IntrinsicElements["app-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLAppAmbulanceWlListElement>;
        }
    }
}
